### ISSUE TITLE
AD Review : some minor editorial comments

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/version-negotiation#116]
Instead of creating separate issues for each minor editorial comments I will put them all in this issue -

1. I am not a fan of having normative language in the definitions. I feel those normative languages are out of context and hard to reason. It is the case for MSL definition. I would suggest that besides definition, we have some description where MSL is used and put the recommended value there.
2. What is the difference between the initial version and original version ? if there is none why do we need to use two different call sign for the same thing?
3. What is Tubes? we need to explain it. otherwise use other example.

**Comment by DavidSchinazi** [comment]
> 1. I am not a fan of having normative language in the definitions. I feel those normative languages are out of context and hard to reason. It is the case for MSL definition. I would suggest that besides definition, we have some description where MSL is used and put the recommended value there.

I personally disagree. Mentioning the recommended value when defining the term makes it easier to understand and implement.

> 2. What is the difference between the initial version and original version ? if there is none why do we need to use two different call sign for the same thing?

Agreed, there was only one mention of "initial version" so I replaced that with original in #120

> 3. What is Tubes? we need to explain it. otherwise use other example.

It's a hypothetical example. That doesn't make it unhelpful.

**Comment by zaheduzzaman** [comment]
> > 1. I am not a fan of having normative language in the definitions. I feel those normative languages are out of context and hard to reason. It is the case for MSL definition. I would suggest that besides definition, we have some description where MSL is used and put the recommended value there.
> 
> I personally disagree. Mentioning the recommended value when defining the term makes it easier to understand and implement.
> 
I think it is important to describe the reasoning behind the recommendation, specially when we are coining the term. This is now lacking the description and terminology section might not the best place to describe it. I don't have a super strong opinion here, but I think describing it better would help.
> > 2. What is the difference between the initial version and original version ? if there is none why do we need to use two different call sign for the same thing?
> 
> Agreed, there was only one mention of "initial version" so I replaced that with original in #120
> 
> > 3. What is Tubes? we need to explain it. otherwise use other example.
> 
> It's a hypothetical example. That doesn't make it unhelpful.
:-) hmm, the example makes little sense if one does not understand the terms used in the example. If "Tube" is a hypothetical term here, then let's just mention that.

**Comment by DavidSchinazi** [comment]
> I think it is important to describe the reasoning behind the recommendation, specially when we are coining the term. This is now lacking the description and terminology section might not the best place to describe it. I don't have a super strong opinion here, but I think describing it better would help.

There was no reasoning, this was pulled out of a hat just like the original MSL from RFC 793. Can you send us a PR describing the reasoning you'd like to see added?

> :-) hmm, the example makes little sense if one does not understand the terms used in the example. If "Tube" is a hypothetical term here, then let's just mention that.

Fair enough, I've added the word "hypothetical" to PR #120
