### ISSUE TITLE
AD review: lack of normative language

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/version-negotiation#117]
https://github.com/quicwg/version-negotiation/blob/e193e1264887ffab5919d529ea21c0023989c1ec/draft-ietf-quic-version-negotiation.md?plain=1#L153

here, it feel lacking normative language. The current text gives feel like there are other options the client can do and these are examples. if that is true what are those other options? if the client behave differently than described here as there is no normative language will that not cause interoperability issues?

**Comment by DavidSchinazi** [comment]
The normative language already exists in [Section 6.2 of RFC 9000](https://www.rfc-editor.org/rfc/rfc9000.html#section-6.2). That said, the QUIC-VN draft is written in terms of QUIC invariants so we should tweak this.

**Comment by zaheduzzaman** [comment]
we should or we should not?

**Comment by DavidSchinazi** [comment]
We should

**Comment by DavidSchinazi** [comment]
#121 takes care of this
