### ISSUE TITLE
Define v1 and draft-29 Compatibility

### ISSUE THREAD

**Issue by nibanks** [quicwg/version-negotiation#12]
The primary versions available to us to test this new version negotiation process are draft-29 and upcoming v1 versions. It probably makes sense to define the compatibility rules for these so that we can test everything out.

**Comment by DavidSchinazi** [comment]
My main concern is that these two versions are very hard to implement compatibility for, because of the TLS codepoint change. Because of that, I don't think Google would implement this. But if we have multiple implementors interested, then we should do it.

**Comment by nibanks** [comment]
I agree it would be tricky. I'd have to double check our logic in MsQuic, but I think it would be easy enough on the server side, but definitely trickier on the client side.

**Comment by DavidSchinazi** [comment]
Since RFC 9000 has been published, I think interest in draft-29 is declining. @nibanks how do you feel about closing this issue?

**Comment by nibanks** [comment]
Sure, good ahead.
