### ISSUE TITLE
Update discipline: tell readers what you update

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#125]
We have agreed to mark this document as updating RFC 8999. Fine, but this lacks a bit of discipline. We should have a statement inside the text (not just the abstract) explaining in which way RFC 8999 is updated.

**Comment by DavidSchinazi** [comment]
Can someone propose text here? Based on our discussion in #115, there is no agreement inside the IETF on what "updates" means so I'm not sure what text would be helpful for readers.

**Comment by huitema** [comment]
@DavidSchinazi see PR #126
