### ISSUE TITLE
Is the server required to upgrade versions?

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/version-negotiation#13]
Let's assume both client and server support compatible versions `X` and `Y`, and the server prefers `Y` over `X`.
The client now initiates a connection using version `X`, for some reason though the conversion from `X` to `Y` fails.

As the draft is written now, the only way for the server to proceed here is to perform Incomptabile Version Negotiation, i.e. send a VN packet. While this rule makes the process deterministic (and might allow the client to verify the result of the version negotiation, see the open question in https://github.com/quicwg/version-negotiation/issues/5#issuecomment-760623428), it also costs a round trip. When the differences between `X` and `Y` are small, a server might prefer to not bother with upgrading the version, and just establish a connection using `X`. Should we allow that?

**Comment by ekr** [comment]
I don't understand the scenario you have in mind here. How would the conversion from X to Y fail? This seems like it shouldnt' happen and should just cause connection failure.

**Comment by marten-seemann** [comment]
@ekr Looking at #11, it says:
> Note that version compatibility does not mean that every single possible instance of a first flight will succeed in conversion to the other version. For example, if version B is equal to A in all aspects except it introduced a new frame in its first flight that version A cannot parse or even ignore, then A could still be compatible with B as conversions would succeed for connections where that frame is not used.

**Comment by ekr** [comment]
OK, well I haven't reviewed #11 but that sounds wrong to me.

**Comment by DavidSchinazi** [comment]
You're right @marten-seemann that was an oversight. In #11, I've replaced:
> If any of these operations fail, the server uses incompatible version negotiation instead, see {{incompat-vn}}.

with:
> If any of these operations fail, the server will use the original version if it supports it, and if it doesn't then the server will perform incompatible version negotiation instead, see {{incompat-vn}}.
