### ISSUE TITLE
Client's version preference is ignored

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/version-negotiation#14]
Assume that both endpoints support compatible versions `A` and `B`, but the client prefers version `A` over version `B`, while the server prefers version `B` over version `A`.

When the server receives a connection attempt using version `A`, it will detect that the client also supports `B`, and convert it to version `B`. The connection therefore ends up with version `B`.

Is that what we want?  One could argue that the version in use should be controlled by the client, not by the server. This could be easily achieved by only allowing the server to switch to version `B` if the client expressed a preference for `B` over `A`.

**Comment by marten-seemann** [comment]
Related: @kazuho's comment on https://github.com/quicwg/base-drafts/issues/4743#issuecomment-760574432.

**Comment by ekr** [comment]
Yes, I believe that having the server choose is the right answer. We already have experience with it in TLS where it works reasonably well. It's also hard to enforce the client chooses rule when the client speaks first and offers all its supported versions. The server can just pretend it only supports B and just speaks the A Initial format.

**Comment by DavidSchinazi** [comment]
I agree with @ekr, letting the server choose whether to follow the client's preference or not seems simplest.
