### ISSUE TITLE
Server behavior when the transport parameter is malformed or conflicting?

### ISSUE THREAD

**Issue by anrossi** [quicwg/version-negotiation#15]
Looking at #11, how should the server respond if the Client Handshake Version Negotiation Information is malformed? For example, the QUIC version in the long header is different from the Current Attempted Version field in the transport parameter?
Should the server continue with the Original Version in the long header (assuming it is supported), or attempt incompatible version negotiation?
(related to #13)

**Comment by DavidSchinazi** [comment]
If the Client Handshake Version Negotiation Information is malformed (too short to be parsed or something like that) or if it fails to validate (e.g. Current Attempted Version field differs from the long header's version) then the server MUST close the connection with VERSION_NEGOTIATION_ERROR. I've added text to #11's "Version Downgrade Prevention" section to make that explicit.

**Comment by marten-seemann** [comment]
According to the principles we used in QUIC v1, I would've expected a TRANSPORT_PARAMETER_ERROR if parsing fails and a VERSION_NEGOTIATION_ERROR if validation fails.

**Comment by anrossi** [comment]
My confusion comes from the line in Compatible Version Negotiation:

> If any of these operations fail, the server will use the original version if it supports it

It seems ambiguous whether this is referring only to the attempt to convert the received flight to a newer version, or whether it  also includes the potential failures in parsing.
@marten-seemann brings up a good point too.

**Comment by DavidSchinazi** [comment]
I see. I've clarified that sentence to explicitly rule out parsing and validation failures. I also changed the error code.

**Comment by anrossi** [comment]
Looks good to me! Thanks
