### ISSUE TITLE
What happens when conversion fails?

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#17]
In [Section 3.3](https://www.ietf.org/archive/id/draft-ietf-quic-version-negotiation-03.html#section-3.3-2) it talks about the server picking a compatible version and then converting the first flight.  As noted in the definition of compatible, it is not sufficient that the transform exist, it also has to succeed.  In the example given, there might be reasons that a conversion could fail (such as the inclusion of information that is optional and cannot be transformed).

In other words, the version might be compatible but the handshake is not.  There are three possible outcomes I see here:

1. This eliminates that version from the set of compatible options.  The server is free to try another compatible version or just give up and use the offered version.  I don't like this much as it implies a denial of service attack on a server that is willing to try multiple compatible versions.
2. The server can regard all attempts at compatible versions to have failed and it could send a Version Negotiation packet in response.  I am happier with this, but only marginally.  It could hide a genuine error on the part of the client.  That error manifests as a performance bug.  As clients should not ever offer a handshake that includes a compatible version that can't be used, this suggests option 3...
3. The server regards this as a fatal error.  The server uses a signal appropriate to the original version to indicate handshake failure.  Ideally, any version that has other versions compatible with it defines an error code for this purpose.

**Comment by marten-seemann** [comment]
> It could hide a genuine error on the part of the client.

Can you elaborate on that? In my mental model, one of the reasons why conversion could fail is that the client is offering an extension which only works with the original, but not the upgraded version. In that case conversion would fail, even though the two versions are compatible in general.

I think this would rule out 3. the client didn’t do anything wrong, and therefore shouldn’t receive an error.

**Comment by ekr** [comment]
On Tue, Feb 9, 2021 at 8:34 PM Marten Seemann <notifications@github.com>
wrote:

> It could hide a genuine error on the part of the client.
>
> Can you elaborate on that? In my mental model, one of the reasons why
> conversion could fail is that the client is offering an extension which
> only works with the original, but not the upgraded version. In that case
> conversion would fail, even though the two versions are compatible in
> general.
>

My view is that either the conversion process should describe how to
discard that data or the client should not include it.

**Comment by martinthomson** [comment]
I agree with @ekr here.  If the conversion hits something that it doesn't know how to convert, which seems possible if you consider the range of options that might exist, then that's an error.  Either client shouldn't have included it, or the server is ignorant of how the conversion should operate.

In most cases I can think of, stuff that is only valid for the original version can just be thrown away when converting.

Concrete example of a case that might fail.  Say that we change the rules for Initial packets in QUICv2 to make the minimum size of the DCID 10 bytes (up from 8 in v1).  A client that offers a QUICv1 Initial with an 8-byte DCID would be valid in v1, but it is invalid in v2.  Thus, the rule might be that the client always provide at least 10 bytes in its DCID.  If the client didn't do that, but offered v2 as compatible, it has a bug and the connection shouldn't proceed.

**Comment by DavidSchinazi** [comment]
I agree with you, though I'm not sure what you're asking in terms of changes to the draft - what's missing? Should we define the concept of conversion better to explain that a conversion cannot fail - or is this about how the server should react when the client sent something that it knew would fail?

**Comment by martinthomson** [comment]
[This text](https://tools.ietf.org/id/draft-ietf-quic-version-negotiation-03.html#section-3.3-2) in Section 3.3 seems to just assume that this conversion process works:

> If the server supports one of the client's compatible versions, and the server also believes that the original version is compatible with this version, then the server converts the client's first flight to that version and replies to the client as if it had received the converted first flight.
