### ISSUE TITLE
Stable address tuple

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#18]
[Section 3.3](https://www.ietf.org/archive/id/draft-ietf-quic-version-negotiation-03.html#section-3.3-4) indicates that the address tuple used for the first flight remain stable.  This is probably OK, but I think that this is unnecessary.

What seems particularly risky here is anticipating the rules about connection IDs that might apply to both versions:

> During that time, clients MUST also use the same Destination Connection ID, except if the server explicitly instructs the client to use a different Destination Connection ID (\[v1 example...]).

My preference here is to drop this text entirely and leave it to the negotiated version to specify these rules.  Once you have performed whatever mapping/transformation that is defined, then the first flight complies with the requirements of the negotiated version and you are subject to the rules of that version.

Trying to manage the intersection of both sets of rules is complicated.  Better not to chase down that rabbit hole (I've been there).

FWIW, I fully expect v2 to also specify address tuple stability during the handshake.  However, if it does not and a client can send a v2 first flight on multiple tuples (leaving aside the implausibility of expecting those datagrams to arrive at the same place), then that won't be naturally compatible with v1 and you won't be able to start with v2 in that way and expect to be able to negotiate v1 out of that.  This is no different than your new, optional frame example.

**Comment by DavidSchinazi** [comment]
I think we need to state something about 5-tuple stability here, because if version A requires 5-tuple stability and version B requires 5-tuple stability, neither of those documents specifies that the two halves of the handshake (the first half using A, and the second half using B) need 5-tuple stability between them.

**Comment by martinthomson** [comment]
I don't think that you need to say anything about that specifically.  You might use it as an example in a sentence like:

> After the first flight is converted to the negotiated version, the handshake completes in the negotiated version.  The entire handshake (including the converted first flight) needs to conform to the rules of the negotiated version.  For instance, if the negotiated version requires that the 5-tuple remain stable for the entire handshake (as QUIC version 1 does), then this applies to the handshake, including the first flight.

**Comment by DavidSchinazi** [comment]
Fair enough, that works for me.
