### ISSUE TITLE
Listing all versions is unnecessary

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#19]
The current approach is somewhat maximal when it comes to listing versions.  This is the most cautious approach, but I am certain that this is unnecessary.  In some cases, that might be bad.

A server does not need to list compatible versions.  A client doesn't benefit from knowing what compatible options the server supports.  It's just wasted bytes.  If the client offered the compatible version and the server supports it, it is not relevant because otherwise the server would have picked it.  If the client did not offer the compatible version, then there is no hope of that being selected either (an alternative outcome to #17 might invalidate this outcome, but I'm assuming that my preferred outcome is what happens there).  Thus, the only requirement is that the server offer information about the versions that are incompatible.

A client does not need to list the versions it received in a Version Negotiation packet.  The information it receives about incompatible versions from the server is sufficient for it to authenticate the information it receives there.

To up-level slightly, I think that the logic we use to determine what is in this field is simple.  The endpoint that decides needs to be presented with an authenticated copy of the information it might use to make its decision.  Thus, the server needs to know about all compatible versions and the client needs to know about all incompatible versions.

To that end, you don't necessarily need to have the client indicate which version it attempted first.  It can just look at the list of incompatible versions the server supports and abort if it sees that version there.

All that said, I think that it is not bad that the client include the current version here.  That's critical information that we aren't necessarily avoiding here.  Note though that this does mean that when you transform a vN Initial to a vM Initial, you can't transform that field, so you have to tolerate this being the *original* version. (I'll open another issue for that.)

**Comment by DavidSchinazi** [comment]
> A server does not need to list compatible versions. A client doesn't benefit from knowing what compatible options the server supports. It's just wasted bytes. If the client offered the compatible version and the server supports it, it is not relevant because otherwise the server would have picked it. If the client did not offer the compatible version, then there is no hope of that being selected either (an alternative outcome to #17 might invalidate this outcome, but I'm assuming that my preferred outcome is what happens there). Thus, the only requirement is that the server offer information about the versions that are incompatible.

As you pointed out, the client and server can disagree on which versions are compatible - so the server can't know the full list of which versions the client thinks are compatible. Or are you just suggesting to remove the versions that the client listed as compatible from this list? That sounds like added complexity to save a very small number of bytes.

> A client does not need to list the versions it received in a Version Negotiation packet. The information it receives about incompatible versions from the server is sufficient for it to authenticate the information it receives there.

How does the server ensure that the version negotiation packet was not tampered with then?

**Comment by martinthomson** [comment]
> the client and server can disagree on which versions are compatible 

I only suggested that the client might make a mistake in constructing its first flight.

I don't think that I ever said that the client and server can disagree.  Or more to the point, I didn't suggest that we deliberately allow one to believe that versions are compatible when the other does not.  That said, I guess it would be possible under what I describe, for either to believe that a version is compatible and the other to disagree.  That might not be good though, because it limits validation options.

However, if you think it through it isn't at all good:
* A client lists version X listed as compatible.  The server supports that version, but doesn't believe it is compatible.  The server can then not choose that version.  The server instead lists that as an incompatible version.  The client would have preferred version X, but chose to offer a more compatible version.  Client is forced to take another round trip to get what it wants.
* A client chooses not to list version X as compatible.  The server believes it is compatible, so omits it.  The client would have preferred it had it known about it, but it isn't able to learn that the server supports it.  (This is the case your design addresses.)

I would rather not to deal with any ambiguity.  I think that support for a version needs to include compatibility, so that if you support X, you automatically understand its compatibility.  If you want definition of compatibility to be separate from definition of a version, then yes, the server might need to list those versions it regards as compatible along with the incompatible ones.

You could make this a per-version thing - if a version *might* be incompatible, then it is listed as incompatible.  That is, if there is an optional compatibility for that version, then you might have to assume that the client doesn't know about that compatibility.  That would be my preference.

> How does the server ensure that the version negotiation packet was not tampered with then?

The only thing that matters to the client is that it is able to authenticate that the versions it might choose in place of the currently offered version are known to it.  You are suggesting that we need to authenticate the bits that were sent in the packet.  We don't need that.  We don't need to list versions that the doesn't support (though of course the server doesn't know that for anything other than greasing versions).  We don't need to authenticate the ordering either.

**Comment by DavidSchinazi** [comment]
From Section 2:
> Note that both endpoints might disagree on whether two versions are compatible or not. For example, two versions could have been defined concurrently and then specified as compatible in a third document much later - in that scenario one endpoint might be aware of the compatibility document while the other may not.

I think that this scenario is realistic, and that's why the current design supports it.

On the topic of validating every single bit of the VN packet, I will say that statements to the tune of "we don't need to authenticate XYZ, just authenticating X is enough" were the source of many of the security vulnerabilities in TLS. I don't feel confident enough to find the exact bounds of what needs to be authenticated, so authenticating everything is safe and principled.

**Comment by huitema** [comment]
I am currently writing the client side code to parse the version_negotiation TP received from the server. It looks like that:

1) Parse the Negotiated Version and verify that it matches the version in the packet header.
2) Parse the Supported Version Count.
3) Verify that there are just 4*count octets of parameter content after the Supported Version Count.

That is, I don't do anything at all with the list of supported versions. I could be wrong, and somebody somewhere might find this list of supported versions useful. But I doubt it.

**Comment by martinthomson** [comment]
The client needs to verify this list or there is a potential downgrade attack.  If you are relying on the server for verifying the copy of the Version Negotiation packet that the client includes, that *might* avoid the attack, but as the client is ultimately responsible for choosing between incompatible versions, it ultimately needs to take responsibility for that choice and that means verifying.

**Comment by MikeBishop** [comment]
The full list might also be useful for client discovery of more-preferred-but-incompatible versions.  If the server accepts the client's proposed version (or upgrades to a compatible version) but also indicates support for some other versions, the client might choose to act on that, either by opening a new connection now or by caching it as a hint for future attempts.

**Comment by huitema** [comment]
Yes, the client might want to do the verification. But then, if the client does the verification, does it need to copy the content of the VN packet in the attribute? We have currently two lists, VN received by client and versions supported by server. At least one of them is redundant.

I actually like the idea of letting the client verify. There is a tradeoff between detecting a spurious VN and junking a connection. In some cases, the negotiation will find the same version that it would have found without the interfering VN. The client is better position than the server to decide the tradeoff.

**Comment by DavidSchinazi** [comment]
Letting the client verify is tricky because we want to support the scenario where
1. client sends initial, reaches server S1
2. server S1 sends version negotiation packet to client
3. client sends initial with a different version, reaches server S2

and S1 and S2 have different supported versions.

The draft currently only relies on server verification because of this requirement: only servers can know about this divergence of versions among a fleet.

**Comment by martinthomson** [comment]
What I proposed for that case is that we allow for S1 and S2 to support different versions, but S2 is required to know that a particular version is unevenly deployed.  S2 would be prohibited from advertising any partially deployed version.

Otherwise, a client can't do the validation, as you say.  As it is the server that has the special needs (that is, it is the one doing a progressive rollout or similar), then it is up to the server to manage that complexity.

**Comment by DavidSchinazi** [comment]
This issue is obsolete now that #42 has landed, closing.
