### ISSUE TITLE
Current Version or Original Version

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#20]
The new transport parameter includes a Current Version.  However, as the client instance of this appears in a message that is "transformed" when selecting a compatible version.  Thus, unless this value is transformed as part of that process (*), I think that this is probably better named as Original Version instead.

Note that I don't believe it to be possible to modify the TLS handshake in any way here.  Though logically the things that carry might be transformed such that the framing is different and so forth, things like the PSK binder in TLS make changes to anything in a ClientHello extraordinarily difficult.  I think that we should accept that some transformations are impossible.

**Comment by DavidSchinazi** [comment]
Are you referring to `Currently Attempted Version`? I personally find that clearer then `Original Version` in that specific context because `Original Version` can be confused with `Previously Attempted Version`.

**Comment by martinthomson** [comment]
"Current" doesn't apply when the transport parameter is validated.  And your text uses "original version" throughout.  I was only requesting that you pick one and be consistent.

**Comment by DavidSchinazi** [comment]
But they're different concepts. Here's an example:

When performing incompatible version negotiation from version A to version B,
1. client sends a first flight with version A where:
  - Original Version = A
  - Currently Attempted Version = A
  - Previously Attempted Version = 0
2. server sends a VN packet which lists B
3. client sends a first flight with version B where:
  - Original Version = A
  - Currently Attempted Version = B
  - Previously Attempted Version = A

**Comment by martinthomson** [comment]
Oh, then I think that you want Attempted Version and Original Version as your field names.

**Comment by DavidSchinazi** [comment]
That doesn't work for compatible VN from A to B, where the client sends a first flight with version A where:
- Original Version = A
- Currently Attempted Version = A
- Previously Attempted Version = 0

**Comment by DavidSchinazi** [comment]
This issue is obsolete now that #42 has landed, closing.
