### ISSUE TITLE
Section 4 is missing a definition of some fields

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#21]
Received Negotiation Version, Compatible Version, and Supported Version each have a description for their counts, but not the fields.  (Some of the definition of these is included in the description of the count; this is just an editorial quirk.)

**Comment by DavidSchinazi** [comment]
Would you like to send a PR for this?

**Comment by DavidSchinazi** [comment]
This issue is obsolete now that #42 has landed, closing.
