### ISSUE TITLE
Don't undermine version greasing

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#22]
> Clients MAY include versions following the pattern 0x?a?a?a?a in their Compatible Version list, and the server in their Supported Version list. Those versions are reserved to exercise version negotiation (see the Versions section of [QUIC]), and MUST be ignored when parsing these fields. On the other hand, the Received Negotiation Version list MUST be identical to the received Version Negotiation packet, so clients MUST NOT add or remove reserved version from that list.

This construction directly undermines greasing by privileging the handling of greased versions.  Please don't do this.

As I alluded to in #19, this doesn't need to match the Version Negotiation packet/datagram contents.  What is important here is that the list doesn't include a version that the client would have preferred to attempt over the current one.  If you validate the server values that way, then you never have to worry about greased versions being different in the two different places.

Indeed, you can have the server offer Version Negotiation packets that include more versions than they claim in their handshake (this being beneficial during the rollout of a fancy new version of the protocol).

**Comment by DavidSchinazi** [comment]
Can you elaborate on how this undermines greasing? All we say is that you can add grease to version lists, but the Received Negotiation Version list needs to be transmitted as an opaque blob. We don't treat greased versions differently on receipt anywhere.

**Comment by martinthomson** [comment]
Well, the second MUST NOT pertains to something that I think should be removed.  But you say "[reserved versions] MUST be ignored when parsing these fields".  That tells implementations to train themselves to recognize greased versions.  At that point, they are no longer treating these as versions that they just don't understand, but something special.  The whole point of using an odd pattern was to ensure that this never happened.

**Comment by DavidSchinazi** [comment]
Fair enough, if we replaced
> Those versions are reserved to exercise version negotiation (see the Versions section of [QUIC]), and MUST be ignored when parsing these fields.

with:
> Those versions are reserved to exercise version negotiation (see the Versions section of [QUIC]), and will be ignored when parsing these fields.

Would that be OK?

**Comment by martinthomson** [comment]
That's all I'm asking for.  (Along with striking the echo of the VN packet, but we'll pursue that separately.  The requirement there is reasonable if you assume that echoing the bits is necessary.)
