### ISSUE TITLE
Version Negotiation terminates a connection attempt

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#23]
> Once a client has reacted to a Version Negotiation packet, it MUST drop all subsequent Version Negotiation packets on that connection.

The draft says explicitly that receiving Version Negotiation terminates a connection attempt.  This isn't consistent with that.  This probably needs to say something like this instead:

> A client that makes a connection attempt based on information received from a Version Negotiation packet MUST ignore any Version Negotiation packets it receives in response to that connection attempt.

**Comment by DavidSchinazi** [comment]
That sounds good to me, can you make this a PR?
