### ISSUE TITLE
Error signaling is a requirement on all QUIC versions

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#24]
Defining an error code for QUICv1 is good, but I think that you need to frame this differently.  It probably needs to be framed in terms of a requirement on all QUIC versions.  So rather than:

> If the connection was using QUIC version 1, it MUST be closed with a transport error of type VERSION_NEGOTIATION_ERROR.

You might say something like:

> Every QUIC version that supports version negotiation MUST define a method for signaling errors related to version negotiation.  This signal is used when validation of the version negotiation transport parameter fails or when a flight cannot be converted by the server to the compatible version \[note: see #17].  For QUIC version 1, this document registers a transport error of type VERSION_NEGOTIATION_ERROR; see {{iana-error}}.

**Comment by DavidSchinazi** [comment]
I like this. Can you make it a PR?
