### ISSUE TITLE
Define something concrete for Retry

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#25]
Allowing Retry to retain the same version makes it a lot harder to define a transform into a compatible version because it means that the entire Retry exchange needs to be accounted for.  As noted, allowing the compatible version selection to be deferred is probably the right answer, because it means that the server generating the Retry doesn't need to unwrap the Initial.  However, I don't think that a naive design like that naturally retains the properties we designed for Retry.

The current text seems to be disavowing any responsibility for dealing with Retry.  I don't think that is acceptable.

A v2 without Retry that is compatible with v1 could just ignore the Retry, but that would lose the protections we specifically built in v1.  What I think needs to happen is that v2 would not be compatible with v1 unless it was able to carry the information the v2 server needs to authenticate the v1 Retry.  That is, there is a function that transforms a v1 Initial that includes a token into a v2 equivalent and there is a mechanism in v2 that provides the same retry_connection_id and so forth...even if v2 doesn't include a similar Retry mechanism natively.

**Comment by DavidSchinazi** [comment]
We explicitly didn't define anything concrete for protocol features that aren't invariant, such as retry. But we could add some guidelines for this. Can you suggest text?

**Comment by martinthomson** [comment]
How about we agree on a design first.  Do you think that this is a reasonable approach?

**Comment by DavidSchinazi** [comment]
Absolutely, if two versions have a similar concept of retry and similar safety mechanisms to protect it, then retry can be made to work with compatible VN if the compatibility doc describes how to convert the retry safety mechanisms.

**Comment by martinthomson** [comment]
So:

1. Endpoints send Retry (or any stateless exchange that is equivalent) in the version that matches the thing they respond to.
2. Endpoints that choose a compatible version can only do so if the compatible version describes how to translate what happened into something the new version can use.

That seems right.

What I find interesting about this is that v2 might define the same retry authentication as v1, in which case it says "if retry happened, then do the same, whether it was v1 or v2 originally".  That's easy.  We might also have a protocol that doesn't bother to authenticate Retry, in which case translation is as simple as "forget that you sent a Retry".  Anything is possible.

**Comment by DavidSchinazi** [comment]
I like this framing. I'll write it up as a PR unless you'd rather do it.

**Comment by martinthomson** [comment]
You're the editor :)
