### ISSUE TITLE
Frame self-description is not a problem

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#26]
In [Section 10](https://www.ietf.org/archive/id/draft-ietf-quic-version-negotiation-03.html#section-10-1):

> Additionally, frames in QUIC version 1 do not use a self-describing encoding, so unrecognized frame types cannot be parsed or ignored (see the Extension Frames section of [QUIC]); this means that new versions that wish to be very similar to QUIC version 1 and compatible with it should avoid introducing new frames in initial packets.

This is not an issue.  If v2 defines a new frame type that can appear in Initial-equivalent packets, then to be compatible with v1 (in both directions) that frame type could simply be optional in v2.  The lack of a self-describing encoding is not an issue as the parsing of the v2 packet is done with knowledge of all the core frame types in v2.  Sure, you can't introduce an extension frame here, but that's true of v1 on its own.

The only way in which a version might become incompatible is if it includes new *information* that can't be inferred from the other version or doesn't have a valid default.

I think that the intent of this was to say that if there is any need for the Initial flight to carry new information that is only consumed by a compatible version, then there is no way for QUIC version 1 to carry that new information by using new frames.  Instead, it has to use a field in v1 that would be ignored by a v1 endpoint.  As v1 defines no real extension points of this sort, the options in this case are limited.

I think that this text can be removed.  Maybe you could talk about the problem of carrying version-specific information in other versions.

**Comment by DavidSchinazi** [comment]
This makes sense. This text was somewhat vestigial from earlier designs of this mechanism.
