### ISSUE TITLE
Is handshake version information invariant?

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#27]
I think that the answer is "no" (see also Betteridge's Law) in that the format is version-specific, but [Section 4](https://www.ietf.org/archive/id/draft-ietf-quic-version-negotiation-03.html#section-4-1) is pretty obtuse about this:

> During the handshake, endpoints will exchange handshake version information, which is a blob of data that is defined below. In QUIC version 1, the handshake version information is transmitted using a new transport parameter, [...]

The first sentence reads as an absolute; the second is clearly narrowly scoped.  But then nothing is said about other versions.

As I mentioned with error codes in #24, I think that the way this needs to be phrased is as a requirement on QUIC versions that support version negotiation.  The requirement is that those protocols need to define a way to carry certain information.  You can then define that information in the abstract when articulating that requirement; again see #24.

The concrete form you choose for v1 then only needs to apply to v1.

**Comment by DavidSchinazi** [comment]
The intention was for the handshake version information to be invariant, and for how it is conveyed to be version-specific. But I agree that we should state that versions need an authenticated way to exchange handshake version information.

**Comment by martinthomson** [comment]
It needs to go further than that.  I think that you need to list, concretely, what information is being authenticated.  And you need to explain the consequences, namely:

> The purpose of this document is to describe (in the abstract) a version negotiation scheme that different QUIC versions can opt into using.  Though this scheme is not invariant, the versions that use this scheme benefit from downgrade protection if they support either incompatible or compatible negotiation.  Versions that define compatibility with other versions additionally benefit from seamless upgrade.
>
> This does not preclude a QUIC versions from not using this scheme, but that version does not realize these benefits.

And then in Section 4, say precisely what information needs to be authenticated in order to achieve this goal, with a concrete definition for how the information is carried in QUIC version 1 transport parameters.

**Comment by DavidSchinazi** [comment]
That works for me.
