### ISSUE TITLE
You have two links to the repo

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#28]
One was automatically added by tools, the other is in the abstract.

Consider removing one or other.

**Comment by DavidSchinazi** [comment]
It would be nice if there was a way to get the tools to mention the mailing list as well, then we could remove this paragraph.

**Comment by martinthomson** [comment]
The tools do mention the mailing list.  I have no idea what happened to yours.

**Comment by DavidSchinazi** [comment]
Do I need to mention the WG or mailing list in the markdown metadata somewhere?

**Comment by martinthomson** [comment]
It might be possible to run `make -f lib/setup.mk .note.xml`.  Try that and see what damage it does.

**Comment by DavidSchinazi** [comment]
```
~/src/draft-ietf-quic-version-negotiation $ make -f lib/setup.mk .note.xml
make: '.note.xml' is up to date.
~/src/draft-ietf-quic-version-negotiation $ make
make: Nothing to be done for 'latest'.
```

**Comment by martinthomson** [comment]
Yeah, I thought so.  You might need to remove the file first.

**Comment by DavidSchinazi** [comment]
That didn't work so I fixed it by hand via https://github.com/quicwg/version-negotiation/commit/0ef639f6790e1cc576a346aaf31a22712f1c2f2d

**Comment by DavidSchinazi** [comment]
Ah I found the issue, fix is here: https://github.com/martinthomson/i-d-template/pull/266

**Comment by DavidSchinazi** [comment]
Now that that's merged, this is fixed.
