### ISSUE TITLE
Terminological precision

### ISSUE THREAD

**Issue by wbl** [quicwg/version-negotiation#32]
Bijective should be symmetric. We're describing a relation not a function.
This is a very minor comment, will send a PR hopefully soon.

**Comment by DavidSchinazi** [comment]
Indeed, my math is pretty rusty :) Totally agree with you, and thanks for offering to write the PR!

**Comment by LPardue** [comment]
@wbl any luck with the PR?

**Comment by wbl** [comment]
I completely forgot about this!

**Comment by wbl** [comment]
https://github.com/quicwg/version-negotiation/pull/33 opened

**Comment by DavidSchinazi** [comment]
Closing now that #33 has been merged.
