### ISSUE TITLE
Need a rationale for changing the outer Version Number

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#34]
The current text says:

- Negotiated Version: The version that the server chose to use for the connection. This field MUST be equal to the value of the Version field in the long header that carries this data.

That means for example a response to a long header packet carrying version 1 would be a long header packet carrying version 2. This discloses to third parties the otherwise hidden version negotiation, which may well be a bad thing. It also introduces a new error mode, since the result of the negotiation is only known after receiving the server's first flight, but the new version is present in the headers at the beginning of that flight. What if the two disagree?

**Comment by DavidSchinazi** [comment]
I agree that it would be preferable to hide the fact that compatible version negotiation is happening to passive observers. 

But how would that work in practice? How does the client know to parse the server's first flight as a v2 flight without getting that information in the long header's Version field?

**Comment by huitema** [comment]
Maybe switch to the new version *after* the first flight?

**Comment by DavidSchinazi** [comment]
You could imagine using the v1 format for all long headers and v2 for short headers. This then becomes a tradeoff between hiding the VN vs having the flexibility of using the v2 format in handshake packets.

**Comment by DavidSchinazi** [comment]
This text was removed in #42, closing.
