### ISSUE TITLE
Do we really need to list the full VN content?

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#35]
The spec directs the client to list all the versions proposed in the VN that it receives, and the server to verify that "it could have sent this VN". The text then goes on to explain how to relax the checks in partially upgraded server farms. I find this a bit problematic for two reasons:

1)  Assessing whether a server "could have sent" a list of Version Numbers is full of interesting corner cases. Should the verification test the order in which alternate versions are presented? What if different servers in the farm have different software stacks? What if the VN was sent by an updated server but verified by a not-updated server?

2) The spec requires the client to remember the content of the VN packet, which is quite possibly malicious, maybe very large. This is a bit unwieldy to implement. It also has the potential to trigger bugs, by invoking rarely used segments of code.

The server will receive the initial version proposed and the negotiated value. Isn't that sufficient? If we need more, why not providing the full list of versions supported by the client?

**Comment by DavidSchinazi** [comment]
I'm not too worried about asking the client to remember one packet worth of data, but I agree with you that we might be able to simplify this. I went with a very conservative approach of validating everything, but I agree that simply including the original version and negotiated version should be enough to prevent downgrades.

**Comment by huitema** [comment]
I am looking at implementing this, and I wonder whether we should be able to simplify. As you said, the VN content is not really required. The server can check whether it would have rejected the proposed version, and that's pretty much sufficient to protect against VN downgrade, except for the "compatibility" issue.

The easiest client side implementation is to provide a list of "currently attempted, previously rejected, all supported versions", without bothering for the "compatibility" test. If we do that, we leave the test of compatibility strictly on the server side, with incompatibility resulting in VN. If the server can parse the message, then the server will pick the "best" version from a list, and document that in the proposed version. There is no real need to list the server supported versions.

**Comment by DavidSchinazi** [comment]
This issue is obsolete now that #42 has landed, closing.
