### ISSUE TITLE
Domain separation requirements

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#36]
@wbl pointed out on the list that there is a risk where different protocols that share credentials are not mutually secure unless there is clean domain separation when using those credentials.  TLS 1.3 tries to do this by adjusting the signature inputs so that there is no risk of overlap with TLS 1.2, which might also make it more likely that other protocols cannot have collisions.  But that's not a guarantee.

This is largely theoretical (you would need to find a transcript in one protocol that would be accepted in the other protocol), but those sorts of attacks are incredibly hard to fix if the mistake is made.  It is easier - and far better - to prevent than fix.  So a note about this is worth including when talking about incompatible negotiation.  Given that we already have uses of incompatible negotiation that reuse credentials, it seems quite likely that there will be more.

Note: the usual advice here is "don't reuse credentials", but no matter how loudly you say that, people will do what they need to do.  We could say "MUST analyze all credential reuse and prove that there are no potential input collisions", but I don't know if that would be effective in practice.

**Comment by DavidSchinazi** [comment]
Adding guidance for designers of new QUIC versions seems reasonable, but I'm not sure what we can do in this spec protocol-wise apart from making sure the version is in the transcript.

**Comment by martinthomson** [comment]
I don't think that we need to directly mention the goofiness in TLS, but it would simply be a note that sharing credentials across different QUIC versions needs to consider (and ideally mitigate) the risk of cross-version confusion.

**Comment by wbl** [comment]
At the meeting I think @DavidSchinazi mentioned that Chrome is using entirely different crypto with the same certificates in their gquic. Once we do that "the transcript" is underspecified across the underlying crypto protocols. And nobody is going to get new certs or a new PKI for their new QUIC version.

**Comment by davidben** [comment]
Yeah, what's now called gQUIC predates all this stuff, including even TLS 1.3. The signature's got a different label prefix, however.

**Comment by DavidSchinazi** [comment]
Based on this conversation, we don't need to change anything in draft-ietf-quic-version-negotiation for this issue. While making sure signatures have different prefixes is important, I don't think it's in scope for this document because it applies to TLS and Google QUIC which is way beyond the scope of this draft. Closing.
