### ISSUE TITLE
Test case, authenticated handshake

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#37]
I am looking at practical use of "compatible version negotiation", and would like to start with the [authenticated handshake extension)[https://www.ietf.org/archive/id/draft-kazuho-quic-authenticated-handshake-01.txt]. That extension redefines the format of the Initial packets to insert a secret in the authenticated data, and thus in the AEAD checksum. This "change of format" is pretty much what we want to support with the VN mechanism: map the new proposed format to a new version, negotiate that new version, use the new syntax for packets carrying the new version.

When doing that, I find interesting issues. For example, what does it mean to "re-process the client's first flight". Which makes me believe that this is probably on the right track...

**Comment by DavidSchinazi** [comment]
Hi @huitema is this issue requesting specific changes to the draft?

**Comment by DavidSchinazi** [comment]
Closing since I'm not seeing any changes required in the draft. Please reopen if you have changes in mind.
