### ISSUE TITLE
What does reprocess the first flight mean?

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#38]
Section 3.3 states:

* If the server supports one of the client's compatible versions, and the server also believes that the original version is compatible with this version, then the server converts the client's first flight to that version and replies to the client as if it had received the converted first flight. The version used by the server in its reply is refered to as the "negotiated version". The server MUST NOT reply with a version that is not present in the client's compatible versions, unless it is the original version.

I am looking at implementing that, and I am really puzzled. Take for example Martin Duke's V2 draft, which merely changes the Initial salt. Reprocess the first flight would mean try to parse it with the new salt, and that would fail.  Or the "authenticated handshake" draft, which require adding a secret into the Initial AAD, but that secret is only present if the first flight was designed for authenticated handshake. I think that the draft needs to be much more precise about this "compatible version" process. It seems that there are three levels:

* packets, which should be parsed and formatted according to the version number in the long header, or for 1RTT packets the version number negotiated during the handshake.

* frames, which generally should be treated independently of the packet format -- unless the target version includes new parameters

* transport parameters and maybe TLS extensions

In Martin Duke's V2 draft, we have a simple case of merely changing the packet format without changing the semantic of frames or parameters, so that's easy. In the authenticated exchange draft, the peers could update from V1 to V-authenticated, but only if they manage to retrieve the required secret from the TLS extensions or the transport parameter. Is that what reprocess means?

The more I think of it, the more I believe that the "upgrade from V1 to Vx" process should be defined as part of the Vx specification. For example, Vx spec might say something like "when upgrading from V1 to Vx, find the Transport Parameter X, Y and Z and use them to initialize Vx parameters A, B and C." Maybe that's part of what a "compatible upgrade" is.

**Comment by DavidSchinazi** [comment]
Hi @huitema, where does the word "reprocess" come from? I don't see it anywhere in the draft. The draft uses the word "convert". For example in Martin Duke's v2 draft, you would convert a v1 initial to v2 by decrypting it with v1 initial keys, setting the version to v2, and re-encrypting it with v2 initial keys. Then you'd be able to process that new synthetic v2 initial. Of course as an optimization your code can skip the re-encryption and just use the parsed result but the concept is to define a conversion between versions.

In the current design, it's totally possible for the "upgrade from V1 to Vx" process to be described in the Vx draft, but it's not required - that allows us to make two versions compatible even if they were developed concurrently in isolation.

**Comment by DavidSchinazi** [comment]
@huitema gentle ping on this - did the latest update to the draft clarify this for you?

**Comment by huitema** [comment]
The spec says:

* If the server supports one of the client's compatible versions, and the server also believes that the original version is compatible with this version, then the server converts the client's first flight to that version and replies to the client as if it had received the converted first flight. The version used by the server in its reply is refered to as the "negotiated version".

(Typo: Should be _referred_, I think)

The text works, but it relies on _the server also believes_. My point is that in order to believe, the server has to be able to convert the initial Vi input into the selected Vx. You may or may not want to outline that. I would prefer if you did.

**Comment by DavidSchinazi** [comment]
Sounds good, I'll write up an editorial PR to address this.
