### ISSUE TITLE
Packet loss during version negotiation

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#39]
Implementing the negotiation in picoquic, I find an interesting corner case.

When receiving an initial packet, picoquic checks whether there is an ongoing connection for the specified IP addresses, ports and connection IDs. If there is one, it verifies that the newly received packet is consistent with what is already in that context -- in particular, the same version ID. But of course, if the server is doing version negotiation, that version has already changed. Which means that the server can only process the repeated Initial packet if it remembers what the original version ID was. Maybe obvious, but maybe something we should see in the spec.

**Comment by martinthomson** [comment]
There's a related wrinkle: if the client first flight is multiple packets, then the server might need to send multiple packets.  It might be forced to acknowledge in the original version a few times until it has all of the packets and can see that a different version is available.  Clients might get packets out of order and so see something like v2, v1, v2, v2...  They can probably drop the odd version packet, but that might not be the best strategy.

**Comment by martinduke** [comment]
This is addressed in the [v2 draft](https://quicwg.org/quic-v2/draft-ietf-quic-v2.html#name-compatible-negotiation-requ):

Do we still need something in VN?

**Comment by DavidSchinazi** [comment]
Since this detail will be pretty specific to the interaction between the two versions at play, the spec for the second version (or whichever spec makes them compatible) is the right place for that guidance. Conveniently, we already have this in the v2 draft. So I'm going to close this with no action. Please reopen/comment if you disagree.
