### ISSUE TITLE
Do applications define compatible versions?

### ISSUE THREAD

**Issue by martinduke** [quicwg/version-negotiation#41]
Two versions might be compatible in the sense that one can convert the Initial Packet from one into the other. But one version might not have the features necessary for an application. There are two ways to mediate this that I can see:

1) The client excludes compatible versions that are inadequate for the app from its TP. This means the QUIC API will need a way for applications to control the advertised versions.
2) Servers understand what capabilities are needed and will not select an advertised compatible version that does not support them.

For incompatible VN, if the server can identify the application based on IP and port, it might scrub irrelevant versions from its VN packet, though I don't know if that's a good idea or not.

**Comment by nibanks** [comment]
When MsQuic implemented this extension, we exposed a configuration option to the app for it to specify its "desired version list". My expectation is that a client would include all acceptable QUIC versions here, and then adapt (if necessary) their protocol layer accordingly. Though, this might get harry, for instance, if they need to then choose a different ALPN based on the negotiated QUIC version (we don't _currently_ support that).

**Comment by DavidSchinazi** [comment]
@martinduke you're describing an implicit assumption of the draft: the list of supported versions are specific to an application, not just to an implementation. Perhaps we can add a sentence to make that more obvious. The client shouldn't be enabling or advertising support for versions that it can't use. Servers don't need to do anything here, it's the client's responsibility to know what it wants to do with a given connection, not the server's.

**Comment by martinduke** [comment]
Yes @DavidSchinazi that works for me. The real issue is that this not totally internal to the QUIC implementation and there needs to be an API for the application to manage this.

**Comment by DavidSchinazi** [comment]
I agree that such an API is reasonable (Google QUICHE provides one for example) but I think that's out of scope for this document though.

**Comment by martinduke** [comment]
I agree you shouldn't define the API, but it would be good to say, "hey, dummy, don't just advertise every compatible version the QUIC implementation supports"

**Comment by MikeBishop** [comment]
Note that the relationship between version selection and ALPN is similar to the aftereffects of HTTP/2, which made the cipher selection and ALPN selection within TLS interdependent. That was a pain. It doesn't affect this draft per se, but I do hope we don't paint ourselves into that particular corner again.
