### ISSUE TITLE
Anthropomorphism

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/version-negotiation#45]
This draft talks about clients and servers "thinking" and "believing" things.  Those verbs don't necessarily apply to protocol implementations, no matter what new frontiers we're exploring in the machine learning space.  Might be worth a pass to rephrase these in terms of client or server capabilities and information.

"Know" is a little fuzzier, since an endpoint does in fact possess information at certain points in the process.

**Comment by janaiyengar** [comment]
So... when my computer says "thinking ...", are you saying it's lying to me?

**Comment by LPardue** [comment]
https://thedailywtf.com/articles/The-Speedup-Loop
