### ISSUE TITLE
The client is unable to detect downgrade attacks

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/version-negotiation#5]
While I recognize that it is an explicit design choice of this extension to move all the downgrade detection to the server, it seems unfortunate to prevent the client from detecting the downgrade and instead relying on the server to do so. (I could imagine that some server implementations are lazy/broken and might not perform this detection)?

Alternatively, if the server delivered to the client a set of lists of versions that the server (or the server's peers) might have sent in VN packets, then the client could compare the actual VN packet it received with the elements in the set and detect the case where none of them match. Commonly the server would send one such list, but if it were participating in a staggered rollout, it could send both the "old" and "new" lists?

(Issue copied from [individual draft repo](https://github.com/ekr/draft-schinazi-quic-version-negotiation/issues/3), by @RyanTheOptimist on 2019-11-04)

**Comment by marten-seemann** [comment]
The `Server Handshake Version Information` contains all versions supported by the server, so the client could easily perform that verification, taking care to:
* remove the current version from `Supported Version`
* remove any greasing version both from `Supported Version` and from the versions in the VN packet
* ignoring the ordering of versions (dependent on the outcome of https://github.com/quicwg/base-drafts/issues/4743)

Open question: Should the client also check that the server actually performed a version upgrade, if there's a version supported by both endpoints with a higher preference than the currently selected version?

**Comment by RyanTheOptimist** [comment]
@marten-seemann, what is "Server Handshake Version Information"? I don't see that string in this draft. Is it in a different doc?

**Comment by marten-seemann** [comment]
Sorry, I was looking at #11, as I assumed that’s the direction this draft is moving in.

**Comment by RyanTheOptimist** [comment]
Oh, I see. Yes, I agree that #11 fixes this issue.
