### ISSUE TITLE
Backward compatibility with the version negotiation of RFC 9000

### ISSUE THREAD

**Issue by kazu-yamamoto** [quicwg/version-negotiation#55]
Suppose that a client supports QUIC v1, v2 and the new negotiation while a server supports RFC 9000 only. 

The following normal scenario succeeds because the client does not receive a VN packet so the client does not have to check `version_information`:

```
- C: Initial: ver=1, version_information = 1, {2, 1}
- S: Initial: ver=1, Handshake
- C: Handshake: ver=1
```

However, the following scenario, I think, fails:

```
- C: Initial: ver=greasing, version_information = greasing, {2, 1, greasing}
- S: VN: ver=0, {1}
- C: Initial: ver=1, version_information = 1, {1}
- S: Initial: ver=1, Handshake
- C: Handshake: CC
```

The client sent CC because `version_information` is missing.

The latter is the common method to test the version negotiation of RFC 9000. Are we giving up this method?

**Comment by martinthomson** [comment]
It looks like the key flaw here is in dealing with servers that don't understand this extension.  I think that we fix that by treating absence of version_information as being equivalent to "version_information = 1, {1}" or "version_information = 1, {}" (which is functionally equivalent).

That is, of course, in tension with this text in [Section 6](https://quicwg.org/version-negotiation/draft-ietf-quic-version-negotiation.html#section-6-3):

> If the Version Information was missing, the endpoints MAY complete the handshake if they have reason to believe the peer might not support this extension. 

... so far so good.

> However, if a client has reacted to a Version Negotiation packet and the Version Information was missing, the client MUST close the connection; if the connection was using QUIC version 1, that connection closure MUST use a transport error of type VERSION_NEGOTIATION_ERROR.

That part probably needs to be revised.

**Comment by kazu-yamamoto** [comment]
With the current spec, "version_information = 1, {}" from a *client* is not allowed. So for simplicity, "version_information = 1, {}" from a *server* should not be allowed, either. Only the form of "version_information = 1, {1}" should be allowed.

**Comment by DavidSchinazi** [comment]
I agree with the premise, the scenario where the client starts with a grease version, waits for VN then tries with a version from the VN packet doesn't work with this extension. But that scenario was never specifically allowed in RFC 9000, it's just something a few implementations picked up along the way. I'd suggest either doing nothing, or having an appendix that mentions this version greasing technique. I'd rather not treat a missing parameter as something present, because that opens up a class of downgrade attacks against servers that don't support this extension.

**Comment by DavidSchinazi** [comment]
Conceptually, this comes down to one question: if the server doesn't support this extension, should the client fail open or fail closed. I'd argue fail closed because it has better security and this scenario won't happen in practice.

**Comment by kazu-yamamoto** [comment]
I don't have a strong opinion. I just want to have a clear spec. 

Let's consider another scenario. Suppose that a server supports RFC 9000 only and does not allow draft-29. If I understand correctly, the following would happen without the greasing version:

```
- C: Initial: ver=draft-29, version_information = draft-29, {2, 1, draft-29}
- S: VN: ver=0, {1}
- C: Initial: ver=1, version_information = 1, {1}
- S: Initial: ver=1, Handshake
- C: Handshake: CC
```

@DavidSchinazi Does this scenario change your opinion?

**Comment by DavidSchinazi** [comment]
The specification for draft-29 states that if you receive VN you MUST close the connection. If you support draft-29 and the VN draft, then you try again but require the presence of version_information and fail the handshake if it's missing. This scenario isn't ambiguous. We need to fail the handshake in this scenario because otherwise we're exposing the client to version downgrade attacks.

**Comment by kazu-yamamoto** [comment]
OK. I would like to add an appendix which describe the four scenarios in https://github.com/kazu-yamamoto/quic/issues/19.

**Comment by DavidSchinazi** [comment]
That's reasonable. Can you send a PR with the appendix you have in mind please?

**Comment by kazu-yamamoto** [comment]
I will.

**Comment by martinthomson** [comment]
> The specification for draft-29 states that if you receive VN you MUST close the connection.

What about if you support version 2 and version 1?  Version 2 will say that you need to support this draft.  But if the server doesn't support version 2, then do you also need to fail on the basis that you are now executing version 1 logic?  That seems like it is the wrong answer.

Sure, most sensible clients will attempt version 1 and offer a compatible upgrade to version 2, but that doesn't mean we shouldn't consider the converse.

**Comment by DavidSchinazi** [comment]
I see two solutions here:
1. Tell the client to not do that - we already have text in the "Client Choice of Original Version" section but we could expand on it
2. Fail open (in other words, don't fail the handshake if version_negotiation is missing)

Do you have opinions on which is best? (or if you see other solutions)

**Comment by martinthomson** [comment]
In this case, we have special information: if the server only supports version 1 (let's not drag pre-RFC9000 draft versions into this), then the absence of the extension might be used to confirm that.  That only works for version 1, but it seems OK to me to accept that as a positive signal (as opposed to the absence of one).

**Comment by DavidSchinazi** [comment]
What about a server that supports QUICv1 and Google QUIC versions Q050 and Q043? Or some other future non-IETF versions? In other words, what change to the draft do you have in mind? We could special-case QUICv1 but I'm not sure what it'd get us.

**Comment by martinthomson** [comment]
My suggestion is that we say that a client that negotiates QUIC version 1 can assume that the server ONLY supports QUIC version 1 for the purposes of validation.  That is, in the absence of the extension and if QUIC version 1 is in use, the client may assume that the extension is present with a value of `1, {1}` (to use Kazu's notation).

That privileges QUIC version 1 as the version of QUIC that we defined prior to this, but I don't think we can extend this sort of compatibility to other protocols without risking the exact sort of downgrades we're trying to avoid.

Sadly, that means that Q050 and Q043 are not protected in the same way.  Implementations of other QUIC versions could add support for this extension though.

**Comment by DavidSchinazi** [comment]
That sounds reasonable to me. If we rely on the following two assumptions:
1. QUICv1 is preferred over earlier versions (such as 0xff00001d or Q050)
2. versions that are created after QUICv1 will use this draft

then we're guaranteed that a downgrade attack against a QUICv1+Q050 server isn't possible, while still allowing VN to servers that only support QUICv1.
