### ISSUE TITLE
Should "Compatible Version" mention 0-RTT?

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/version-negotiation#6]
Consider the case of two difference QUIC versions which are roughly identical in terms of the crypto/handshake/packet layer. But imagine that these two versions, say, renumber streams or some other change which makes 0-RTT data look different. I would assume that such versions would not be "compatible" for the purposes of section 7?

Or alternatively, they could be considered compatible, but the server MUST not process 0-RTT packets, and the client must "unwind" the 0-RTT state (un-open streams, etc)?

(Issue copied from [individual draft repo](https://github.com/ekr/draft-schinazi-quic-version-negotiation/issues/2), by @RyanTheOptimist on 2019-11-04)

**Comment by DavidSchinazi** [comment]
[Comment](https://github.com/ekr/draft-schinazi-quic-version-negotiation/issues/2#issuecomment-549562670) from @DavidSchinazi on 2019-11-04:

I agree, we should add text to discuss this, perhaps in a section of recommendations for writers of new versions. When deciding whether two versions are compatible, the cost of rewriting 0-RTT data from one version to the next should be taken into account.

**Comment by DavidSchinazi** [comment]
[Comment](https://github.com/ekr/draft-schinazi-quic-version-negotiation/issues/2#issuecomment-555826187) from @grmocg on 2019-11-19:

Interested in seeing where this goes.

**Comment by MikeBishop** [comment]
It definitely should discuss 0-RTT.  I suspect the same language *could* hold, in that for certain pairs of versions it might be possible to construct up-level 0-RTT packets from down-level 0-RTT packets and pretend that's what you received.  However, I suspect that won't be true for all compatible version pairs; tolerating that would mean that you have versions which are Initial-compatible and versions which are I/0-compatible, and you'd have to define behavior between them.

It might be simpler to say that if the server wants to change versions, it MUST reject Early Data.
