### ISSUE TITLE
Specify impact on encryption keys

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#67]
I am reading the draft, and I have doubts on how this is supposed to affect encryption keys.

Suppose a classic exchange: the client sends a couple of initial packets, the server parses them and acknowledges them, the server then sends initial and handshake packets. I think we have the following constraints:

1) The server will only complete the compatible version negotiation after receiving "enough" of the client's initial packets, i.e., enough to parse the QUIC transport parameters.
2) The server transport parameters are sent as encrypted extensions. The client will only receive them after receiving "enough" handshake packets.
3) The client could learn that the server has chosen a new version at any point during the handshake, by receiving a new version field in a long header packet --  Initial or handshake.

So we get possible variations:

1) Server receives client first flight with V1, may reply with V1 ACK until the flight has been received, but uses V2 for the reminder of the handshake, i.e., sends server hello in a V2 Initial packet, sends the encrypted parameters and the reminder of the server first flight in V2 handshake packets. Upon reception and successful decryption of initial V2 packet, the client switches to V2.

2) Same but server sends all Initial packets using V1, all handshake packets using V2. Client switches to V2 upon reception and successful decryption of V2 handshake packet.

3) Server keeps using V1 for initial and handshake packets, switches to V2 for 1RTT packets. Client keeps using V1 until the handshake completes, switches to V2 for 1RTT packets.

Variation 3 is the easiest to implement, but I suspect that "the server converts the client's first flight to that version and replies to the client as if it had received the converted first flight" actually implies variation 1. That variation requires that the client makes a pretty expensive decision, recomputing the encryption keys using the new version's parameters upon receiving a packet with a "negotiated" version in the version header. Since the encryption key of initial packets is well known, this is yet another avenue for third parties to send poisoned packets and cause the client to fail the connection, but I suppose that will not stop us because there are many such attacks already.

In any case, the current text is not very explicit. I think that we will save a lot of interop issues by being more explicit, maybe presenting the expected flow of packets.

**Comment by kazu-yamamoto** [comment]
I agree that timing of key installation is severe. From the anti-ossification point of view, V2 should be used as much as possible. So, variant 1 is ideal but it is hard to implement it.

**Comment by huitema** [comment]
I am doing a thought experiment, hypothesizing a V3 version of QUIC in which the handshake changes radically. Instead of using just Initial and Handshake packets, the Handshake would also use Zero RTT packets, because we magically found a way to always have a Resume Token available, or maybe a shared password. In the new V3 version we would have:

* From client: Initial packet carry Client Hello and some unencrypted parameters. 
* From client: Zero RTT packets carry encrypted handshake parameters
* From server: Zero RTT packets carry Server Hello and unencrypted extensions. 
* From server: Handshake packets carry reminder of server flight
* From client: Handshake packet carry Client's Fin.

Maybe V3 is designed to prevent third parties from spoofing the server. In the transition phase, we would want something like:

* From client: Initial V1 packet carry Client Hello and all parameters. 
* From server: Zero RTT V3 packets carry Server Hello and unencrypted extensions. 
* etc...

That would preserve the key "defense from spoofing" when the negotiation succeeds. But it does require something like variation #1.

**Comment by DavidSchinazi** [comment]
The current text in the draft was written with Google's implementation in mind, where the server will never send a packet until it has received the full client hello. Therefore the intent was:
* client sends first flight in v1
* if some of those packets get lost, the client retransmits all of them
* once server receives the full client hello, it can decide to perform compatible VN with v2
* all server packets are then sent with v2

This issue makes me realize that some implementations may wish to acknowledge initial packets before receiving the full client hello, which I hadn't thought of. If the client hello ever becomes more than a handful of packets, this might be useful.

I would prefer variation 1 (server sends initial acks of client's first flight in v1 but everything else in v2, including the server hello) as that would match our implementation model, and has the property of switching to the newer version ASAP.

I agree that we should be clearer, though I'm not sure if that belongs in this draft since this draft intends to be mostly version agnostic. Perhaps that's something that needs to be added to the QUICv2 draft in the section when it declares itself compatible with QUICv1?

**Comment by kazu-yamamoto** [comment]
Yes, it would be nicer if we add VN scenarios to the V2 draft instead of the VN draft.

**Comment by huitema** [comment]
I think you cannot pass the burden to every new version draft. You have to be very explicit about what is expected.

On the implementation part: picoquic uses picotls. When initial or handshake packets are received, picoquic passes the content of the "crypto" frames to picotls. Picotls does its own thing according to the TLS 1.3 logic. At some point it will callback into picoquic for events like "handshake secret is now available" or "transport parameter option has been received". In my tests, the order of events on the client was:

1. set zero RTT encode secret (when sending the client hello)
2. receive the server initial packet with new version set (which causes client to declare negotiation successful)
3. set handshake encode secret (when receiving the server hello extensions)
4. set handshake decode secret (when receiving the server hello extensions)
5. process the transport options (when receiving the server first flight)
6. set the 1rtt encode secret (after receiving the server first flight)
7. set the 1rtt decode secret (father receiving the server first flight)

On the server, the order is:

1. set the zero RTT decode secret (when receiving the client hello)
2. process the transport options (when receiving the client hello) and do the negotiation
3. set handshake encode secret (after composing the server hello)
4. set handshake decode secret (after composing the server hello)
4. send the server initial packet with new version set (which causes client to declare negotiation successful)
6. set the 1rtt encode secret (after sending the server first flight)
7. set the 1rtt decode secret (father receiving the client finished)

In the specific case of the V1 to V2 "reprocessing" means replacing the initial key computed with the V1 initial secret by one that uses the V2 secret. However, on the client side, we have to do this reprocessing in a speculative manner, upon receiving a first long header packet with version = V2.

**Comment by huitema** [comment]
There is something weird happening with 0-RTT. See issue #68

**Comment by DavidSchinazi** [comment]
> I think you cannot pass the burden to every new version draft. You have to be very explicit about what is expected.

I don't understand, how can this draft be explicit about future versions that don't exist yet?

> In the specific case of the V1 to V2 "reprocessing" means replacing the initial key computed with the V1 initial secret by one that uses the V2 secret. However, on the client side, we have to do this reprocessing in a speculative manner, upon receiving a first long header packet with version = V2.

Is that a problem?
