### ISSUE TITLE
Specify impact on 0-RTT, session resume tickets, etc.

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#68]
0-RTT is a weird case. 0-RTT packets are sent by the client using the "old" version, but they will be received by the server after the server has completed the negotiation to the new version. There are many plausible solutions, such as:

1) Do not do both 0-RTT and version negotiation. If a session resumed ticket was received after negotiating from version=A to version=B, then the resumed connection shall use version=B.
2) Accept that 0-RTT packets are decrypted with version=A.
3) Maybe let clients recompute the 0-RTT key after the negotiation completes.

All of these have pros and cons, but they should be specified.

**Comment by DavidSchinazi** [comment]
Interaction with 0-RTT is discussed in [Section 9](https://datatracker.ietf.org/doc/html/draft-ietf-quic-version-negotiation#section-9). What's missing?

**Comment by huitema** [comment]
It is probably possible to express the issue in a version independent way.

Something like:

  * Client sends a first flight composed on Version A packets
  * Midway through that flight, server receives enough data to decide to upgrade to version B
  * Server keeps receiving Version A packets for some times after the upgrade
 
 Upgrade specification shall say what to do with these "after upgrade" packets.

Also, you probably want to say how negotiation interacts with session resume. Shall the client remember that this particular session resume ticket was received after negotiating version B? Is it OK to just attempt to resume using version B? What does that do to server farms and partial upgrades? If the server farm is not completely updated, should servers list the version B in their supported version list?

**Comment by DavidSchinazi** [comment]
> It is probably possible to express the issue in a version independent way.
> 
> Something like:
> 
> * Client sends a first flight composed on Version A packets
> * Midway through that flight, server receives enough data to decide to upgrade to version B
> * Server keeps receiving Version A packets for some times after the upgrade
> 
> Upgrade specification shall say what to do with these "after upgrade" packets.

My impression is that Section 9 pretty much says this already, but perhaps I'm misunderstanding what you're looking for. Could you send a PR with what you have in mind?

> Also, you probably want to say how negotiation interacts with session resume. Shall the client remember that this particular session resume ticket was received after negotiating version B? Is it OK to just attempt to resume using version B?

As far as I can tell, TLS 1.3 session tickets aren't tied to a transport or application protocol, so they can be used across QUIC versions, right?

> What does that do to server farms and partial upgrades? If the server farm is not completely updated, should servers list the version B in their supported version list?

This is discussed in [Section 2](https://datatracker.ietf.org/doc/html/draft-ietf-quic-version-negotiation#section-2).

**Comment by martinthomson** [comment]
I think that the draft should say that a client that receives a session ticket MUST remember the version that was negotiated in that session and attempt a connection with that version only when using the ticket.  The server MAY reject resumption if the ticket version doesn't match.

Yes, you could just resume with TLS and do a concurrent version upgrade.  TLS won't care, but your application state might if it cares about version-specific capabilities.  Especially with 0-RTT.  I don't see much point in engaging with that.  Just require that the version stay the same.

**Comment by huitema** [comment]
I believe that we may want different behavior based on whether or not the negotiated version supported. Suppose two connections in which the client initiated a connection with version A. In the first, the server parameters contain:
* negotiated: version B
* supported: [ version A, version B]
In that case, I think we agree that the client should resume using version B, and may use 0RTT.

In the second case, the server parameters contain:
* negotiated: version B
* supported: [ version A]

For me the second variant indicates that the server would like further connections to be initiated with version A. Could be for many reasons, but a common one would be partial deployment of version B in a server farm. In that specific case, the client may well want to resume with version A and use 0RTT of version A.

**Comment by martinthomson** [comment]
This is good input.  I think that we might recommend something like that, though I don't think we need to go any further.

**Comment by martinthomson** [comment]
I was originally convinced of the merits of Christian's approach here (I even opened an issue on our implementation to consider it), but I've since revised that.  Though - in theory - this is right, the chances that resumption is needed during the time that a cluster is partially upgraded is small enough that I don't think that it's worth the extra complication.

If you have a server cluster that is rolling out v2, then it might be that you choose v2.  When the client later resumes, presumably the cluster is further along with their rollout, making the odds of hitting a v1-only node low.  Even with an extended rollout and a rapid resumption, which should be rare, the cost of that is a Version Negotiation packet and a full handshake: one round trip extra, maybe two.  Given the transient nature of rollouts, this seems workable.

Rollback is the other case where you might encounter this sort of skew.  That is something that generally only happens when things have gone pear-shaped, so I'm not going to worry too much about some extra latency there.

**Comment by huitema** [comment]
@martinthomson you are assuming that a significant time elapses between initial connection and resumption. That assumption may not be true for all applications. In DoQ for example, resumption is used as an alternative to keep-alive. The interval between connection may well be on the same order of magnitude as the idle timeout -- 10 or 20 seconds.

**Comment by martinthomson** [comment]
That seems enough that circumstances could have changed, or at least that failed resumptions won't adversely affect performance.

**Comment by huitema** [comment]
I am trying to think how these issues play out at the TLS level. Are we going to require that implementations encode the version number in the resumption token? If we don't, then there is hardly any enforcement possible, and the arguments behind use-it-or-lose-it come to mind. But then, can implementations actually tie a TLS resumption token to a QUIC version? I think I could implement that in Picoquic, but given the "black-box" API between TLS and QUIC, I would not assume that all implementations can.

Then there is of course the whole issue of tying -- or not -- versions of QUIC to versions of TLS. Or, for that matter, using something else than TLS in a future version of QUIC.

And there is a specific case of V1->V2. There is no actual functional benefit to V2. If there is a performance cost, then the upgrade is going to only be used rarely...

**Comment by martinthomson** [comment]
It's trivial in my implementation, black box and all.  That is, if you do 0-RTT, you have to remember a bunch of stuff with tickets, so this is just one more piece of data (4 bytes at most).  So implementation-wise, I can't see any issue.

Keep in mind that this performance cost occurs rarely, only during times when a cluster has uneven support AND when that uneven support covers a connect-resume cycle.  Seems like it isn't worth solving generically.

**Comment by huitema** [comment]
It is trivial to do that in a client implementation. Not so much in a server implementation, especially those that put all the state in the encrypted token. That gets a bizarre tradeoff in which clients can decide to abide by the matching token version requirement although it might in some case impede performance, but servers have a hard time enforcing that requirement.

**Comment by DavidSchinazi** [comment]
Why is this not trivial on the server? Since servers already need to encode TPs and h3 settings as a binary blob in the ticket, adding the version to that blob should be trivial right?

**Comment by huitema** [comment]
Servers do not need to use the initial settings -- this is only for clients sending 0-RTT. The servers only sends data after the negotiation has been done. Servers may need to verify that the client is not sending something excessive in 0-RTT, but they have a very good idea of what initial parameters they use by default, and thus do not need to replicate them in the blob. Might be interesting to ask server developers what they actually do.

**Comment by DavidSchinazi** [comment]
The h3 draft states:
> A server can remember the settings that it advertised, or store an integrity-protected copy of the values in the ticket and recover the information when accepting 0-RTT data. A server uses the HTTP/3 settings values in determining whether to accept 0-RTT data. If the server cannot determine that the settings remembered by a client are compatible with its current settings, it MUST NOT accept 0-RTT data. Remembered settings are compatible if a client complying with those settings would not violate the server's current settings.

So the server needs to store _something_ about settings. It could be the full settings, a hash, or just a number, but it needs _something_ if it wants to be able to ever change its settings without rotating session ticket keys at the same time.

Speaking as a server developer, our stack serializes the entire settings frame into the ticket.

I could imagine a server just rotating their keys when they change settings or transport parameters and not having to store data in the ticket, but it's pretty much required if you want to support multiple keys at once which is required for good performance with proper key rotation practices.

**Comment by martinthomson** [comment]
> Speaking as a server developer, our stack serializes the entire settings frame into the ticket.

So THAT's why they are so huge!  (Seriously though, that's exactly what we do as well, even though our server is not deployed in quite the same way, it's the easiest thing to do.)

**Comment by huitema** [comment]
OK, Google and Mozilla. I am almost convinced. Care to ask the wider group?

**Comment by huitema** [comment]
The nice thing there is that it trains middleboxes to support very large resumption tickets. I can think of quite a few hacks based on that property...

**Comment by DavidSchinazi** [comment]
The normative requirement on servers is unenforceable, so I'd suggest adding it anyway - since most servers will enforce this, clients will do the work of not reusing across versions, so even servers that do not enforce will ultimately be safe. I'll write up a PR to the VN draft that mentions this in vague terms, and filed https://github.com/quicwg/quic-v2/issues/31 to add normative text to the QUICv2 draft.
