### ISSUE TITLE
How can the server chosen version field be empty?

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#69]
The draft says:

_Server-Sent Other Versions:

    When sent by a server, the Other Versions field lists all the Fully-Deployed Versions of this server deployment, see Section 2. Note that the version in the Chosen Version field is not necessarily included in this list, because the server operator could be in the process of removing support for this version. For the same reason, this field MAY be empty._

But the syntax is:
```
Version Information {
  Chosen Version (32),
  Other Versions (32) ...,
}
```
What does the draft exactly mean by "_this field MAY be empty_"?

**Comment by DavidSchinazi** [comment]
The "Other Versions" field contains a list of versions, whose length can be zero. That text exists to remind people that the list of Fully-Deployed Versions can be empty, and that shouldn't cause handshake failures.

**Comment by huitema** [comment]
The text is far from clear, because the sentence mixes references to "Other Versions" and "Chosen version". Stating "For the same reason, the Other Versions field MAY be empty" would remove the ambiguity.

**Comment by DavidSchinazi** [comment]
Thanks for clarifying, I've written that up as #71.
