### ISSUE TITLE
Security issue when upgrading based on received version in header

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#70]
The exchange with a successful negotiation may look like:
```
    Initial packet, long header, version=A ---->
                   [server receives transport parameters]
            <---- server response, long header, version=B
            <------- more packets, long header, version=B
    [client receives transport parameters]
```
The discussion of issue #67 shows the value of having the server switch to the new version as soon as the negotiation completes. But then, the client can only decrypt the server response if it verifies that "version = B" is an expected response, and then starts using the version B encryption keys, etc.

There is very little protection there. Are we worried that third parties might spoof a successful negotiation?

**Comment by ekr** [comment]
I'm not sure I understand the problem here. The version will be retroactively blessed when the handshake completes, just like the rest of the handshake negotiation.

**Comment by DavidSchinazi** [comment]
+1 to what @ekr said.

@huitema this is addressed in [Security Considerations](https://datatracker.ietf.org/doc/html/draft-ietf-quic-version-negotiation#section-11):

> Negotiation between compatible versions will have the security of the weakest common version.

**Comment by huitema** [comment]
Yes, I get that the whole posture is "best effort until the handshake is complete, detection of issues during the completion", and that the final verification will detect spoofing and terminate the connection. So this is basically one more avenue for injecting spoofed packets during the handshake, causing the connection to crash. We may or may not want to mention that.

**Comment by DavidSchinazi** [comment]
It's already trivial to cause a handshake failure by injecting spoofed packets, this doesn't make it any worse. So I don't think we absolutely need to mention this but I wouldn't oppose an addition to Security Considerations if you want to write a PR.

**Comment by huitema** [comment]
I am implementing that right now, and I am trying to understand when to accept this "automatic" negotiation. This may be a V1 only issue, but I suspect we will find it with other versions as well.

The basic protection is that packets received with the wrong version are considered bogus, and are just ignored. I need to create an exception to that rule when negotiation is in progress, accept packet if the version would be accepted after successful negotiation, and do as if the negotiation had already succeeded. The obvious restriction is to only do that on the client, before the handshake is complete. But that still opens a large time window for attacks.

Restricting to "TP negotiation not complete yet" is a bit better than "handshake not complete yet", but still leaves a large window. Restricting to "this is the first packet from the server" does not work, because the server could be sending initial acknowledgements. Reasoning such as "no crypto frame received yet" might work, but the existence of "crypto frames" is version dependent.

**Comment by DavidSchinazi** [comment]
@huitema what problem are you trying to solve? As long as initial receive keys are present, it's trivial for an attacker to make the handshake fail. The version field doesn't change that in any way, and doesn't offer any protection. Or am I misunderstanding something here?

**Comment by huitema** [comment]
There is indeed a denial-of-service window lasting as long as initial packets are accepted. It stops when the handshake keys are computed, at which point picoquic stops processing initial packets. I am trying to ensure that supporting version negotiation  does not extend that window.

But yes, I fully get the general point. If we want to protect against packet injection during the handshake, we have to use some crypto. Maybe derive a token from ECH, or something like that.

**Comment by DavidSchinazi** [comment]
Thanks, I totally agree with your goal. So far I don't see any vector by which this draft extends the DoS window, but adding text to Security Considerations (or perhaps to Considerations for Future Versions) could help ensure we avoid this pitfall in the future.

**Comment by martinduke** [comment]
As we've merged this into the quicv2 draft, is there anything else to say in VN?

**Comment by DavidSchinazi** [comment]
Between what we have in the QUICv2 draft and PR #87 here, this should be covered. So I'm going to close this with no action. Please reopen/comment if you disagree.
