### ISSUE TITLE
Current version in version info breaks transport parameters design patterns

### ISSUE THREAD

**Issue by huitema** [quicwg/version-negotiation#74]
All the transport parameters standardized so far follow a specific pattern: the server can format its transport parameters at the beginning of the connection without waiting for the value of client parameters. Including the "current version" in the "version_information" transport parameter breaks that pattern.

Proposal: remove the "current version" field from the transport parameter.

The current version is already documented in the transport header, so removing that should have minimal effect. But it would remove the opportunity to easily tampering by middle-boxes.

**Comment by martinthomson** [comment]
So I don't think that the pattern extends across versions.  That is, you might be able to unilaterally construct transport parameters for a connection once you decide what to do, but deciding on a version happens before that.

Having the version in the TLS handshake transcript is useful.  Then we are assured that both endpoints agree on that value.  Remove it and we lose that.

**Comment by DavidSchinazi** [comment]
+1 to what MT said, the Chosen Field is required to avoid downgrade attacks. Breaking the pattern isn't a problem to me.

**Comment by huitema** [comment]
I agree that the functionality is worth breaking this established pattern, and that we should not remove the "current version" field. Maybe acknowledge that we are breaking the pattern, and give explicit reasons like detect tampering by intermediaries and have the negotiated version in the TLS handshake transcript.

**Comment by DavidSchinazi** [comment]
@huitema is this pattern documented somewhere? If it's just happenstance I'm not sure it needs to be mentioned?

**Comment by huitema** [comment]
It is mostly tradition. I don't believe it is documented, except maybe in email threads.

**Comment by DavidSchinazi** [comment]
Then do we need to say something in the draft? This issue is as discoverable as those email threads :-)

**Comment by kazu-yamamoto** [comment]
This change effects my implementation where a TLS thread is launched with static TP values in the server side when the first Initial is received.

But according to #72 and #73, Chosen Version is important. I'm getting accept this change.

**Comment by DavidSchinazi** [comment]
Based on this conversation, it doesn't look like there are any changes needed to this draft. The fact that we're breaking a tradition does not need to be covered here since the tradition itself is not covered in RFC 9000. So I'm going to close this with no action. Please reopen/comment if you disagree.
