### ISSUE TITLE
A value of 0 in the transport parameter

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#76]
Should an endpoint be required to reject a transport parameter that contains 0?

**Comment by DavidSchinazi** [comment]
Sure.

**Comment by kazu-yamamoto** [comment]
CC with `TRANSPORT_PARAMETER_ERROR`?

**Comment by martinthomson** [comment]
That's what I currently have in my implementation :)

**Comment by kazu-yamamoto** [comment]
Off topic but what if version 0 is included in Supported Version of a VN packet?

**Comment by DavidSchinazi** [comment]
That would make the VN packet malformed. I'd suggest either dropping such packets or ignoring the zero.

**Comment by kazu-yamamoto** [comment]
OK. I modified my client to drop such packets as same as the case of the original version included.

**Comment by martinthomson** [comment]
I considered treating it as an error, but as it is an unauthenticated packet, it's better to drop it.  I've done the same for ours.
