### ISSUE TITLE
Fix definition of "compatible"

### ISSUE THREAD

**Issue by ghost** [quicwg/version-negotiation#77]
Section 9 is pretty clear that 'compatible versions' might not have commonly usable 0-RTT packets. But Section 3 defines 'compatible' as a translatable first flight. 0-RTT is part of the first flight, so one of these definitions has to change.

**Comment by DavidSchinazi** [comment]
That doesn't necessarily follow. You can translate a first flight in a way that 0-RTT is rejected and the 0-RTT packets are just dropped and the handshake will still succeed. I'm not sure I see an inconsistency here.

**Comment by martinduke** [comment]
Having read sec 3 a few times now, I see the subtlety in your point. 0-RTT could fall under the third paragraph as something that can't be included to be compatible.

I still don't really like the definition. I'll think on it some more, but I'd prefer something like
"A is said to be 'compatible' with B if the first flight of A contains all the information minimally necessary to complete a first flight of B."

So to be compatible with v1 , v_x needs to contain a TLS 1.3 client hello including TPs for version negotiation and all the other required v1 TPs. For v1 to be compatible with v_x, v_x must not have any additional information to complete its first fligth besides the client hello at the v1 TPs.

Whether or not there's 0-RTT in the flight doesn't matter.

We are drifting into the editorial, but if you like that definition I'm happy to write a PR.

**Comment by DavidSchinazi** [comment]
I'm not sure "minimally necessary" is well-defined. How about something like:

> If A and B are two distinct versions of QUIC, A is said to be "compatible" with B if it is possible to take a first flight of packets from version A and convert it into a first flight of packets from version B. As an example, if versions A and B are absolutely equal in their wire image and behavior during the handshake but differ after the handshake, then A is compatible with B and B is compatible with A. Note that the conversion of the first flight can be lossy: some data such as QUICv1 0-RTT packets could be ignored during conversion and retransmitted later.
