### ISSUE TITLE
What is the negotiated version during the handshake?

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/version-negotiation#79]
The [editor's copy of the v2 draft](https://quicwg.org/quic-v2/draft-ietf-quic-v2.html#name-version-negotiation-conside) currently states:
> Both endpoints MUST send Handshake or 1-RTT packets using the negotiated version. An endpoint MUST drop packets using any other version.

Let's assume the following scenario:
* the server supports both v1 and v2, and is configured to perform compatible negotiation from 1 to 2 when possible
* client sends a QUIC v1 initial with "Other Versions" = (1, 2)
* the server decides to switch to v2, and sends its initial ServerHello as v2, followed by a v2 handshake packet with the first half of the certificate - the transport parameters will follow in a later packet
* when the client receives the v2 handshake packet, it technically doesn't yet know the "negotiated version" because it hasn't yet parsed the transport parameters

Conceptually, this sounds like a terminology issue with the VN draft: at that point in time the client does know that the server wants to use v2, because it's parsed a v2 ServerHello - but I think we need a name for that in the VN draft so that the v2 draft can refer to it for the MUST above.

cc @martinduke @martinthomson -- the more I think about it the more I think that [MT's suggestion](https://github.com/quicwg/version-negotiation/pull/42#discussion_r630689250) to "use instead of validate" is making the spec and implementation writing a lot harder - the idea makes sense in theory, but in practice it complicates the handshake. Maybe we go back to something like "the negotiated version is the one seen in long headers, and the Chosen Version in the TP exists to validate that it matches after the fact"

**Comment by martinduke** [comment]
I agree. Let's get the terminology right.

**Comment by martinthomson** [comment]
This WFM.

FWIW, my implementation at the client uses long header packets to "negotiate" the version at the client; the transport parameters are used at the server.  Validation at the server is not necessary, but the validation based on a chosen version is right for the client.

**Comment by martinduke** [comment]
My reading of the current editors' draft is that this is a no-op: AFAICT, the term "negotiated version" refers to whatever is the version field of the first server flight. If the editors agree, please close this issue.
