### ISSUE TITLE
Client Offer Version-Specific Transport Parameters

### ISSUE THREAD

**Issue by nibanks** [quicwg/version-negotiation#8]
Related to https://github.com/quicwg/base-drafts/issues/3965.

Should the version negotiation transport parameter allow for (optionally) encoding transport parameters specific to each compatible version? This might improve the range of compatible versions in the future.

For instance, if version 2 changed the meaning of one of the existing transport parameters such that it wasn't directly compatible with version 1's TPs, this would allow the versions themselves to still be considered compatible, because the client could just offer the v2 TPs along with the v1.

**Comment by DavidSchinazi** [comment]
@nibanks I'm not sure I understand the problem that this solves. If there is a v2-only TP, the client can send it in v1 and rely on the fact that v1 servers ignore unknown TPs. Could you write up a specific example where this would be useful?

**Comment by nibanks** [comment]
Any kind of breaking change to an existing transport parameter, where the new encoding format in v2 is incompatible with v1.

For instance, say `max_udp_payload_size` was changed to require two numbers, a v4 and v6 specific value. I know this is a contrived example, but if something like it happens in the future, the client cannot send a value for 'max_udp_payload_size` that generically works for both v1 and v2. Without this feature, v1 and v2 would have to be considered incompatible.

Another example, would be a transport parameter that is explicitly disallowed to be sent by the client in v1, but then is allowed (required?) in v2. If it's not required, the client just wouldn't be able to take advantage of the feature tied to the TP, but if it goes from disallowed to required, then the versions become incompatible.

**Comment by DavidSchinazi** [comment]
This doesn't sound like the right solution. If we want to change the format of `max_udp_payload_size` in v2, we can give it a new TP ID. That allows the two versions to be compatible. Similarly, if we want to switch a TP from disallowed to required, we can give it a new ID.

Do you have any use-cases that can't be solved by changing the Transport Parameter IDs when changing a TP's meaning?

**Comment by nibanks** [comment]
What about if any transport goes from required in v1 to disallowed in v2?

**Comment by DavidSchinazi** [comment]
As I mentioned in https://github.com/quicwg/version-negotiation/issues/8#issuecomment-665880750 , in that scenario we'd give this TP a new ID in v2.

**Comment by nibanks** [comment]
Yeah, I guess. You just never have a breaking change by constantly appending new transport parameters and ignoring old/deprecated ones. Then the client just sends the superset of all parameters for all versions. It just means you can never actually change the meaning of a transport parameter for with a particular numeric value. If folks are fine with that restriction for transport parameters, then I'm fine closing this issue.

One thought though then, when connecting using version negotiation, the client might use the lowest compatible version number for the packet, but it should supply the highest compatible (superset) version of the transport parameters. Does the spec call this out already?

**Comment by MikeBishop** [comment]
However, as noted in https://github.com/quicwg/base-drafts/issues/4369, we have created such a breaking change between draft versions and version 1.  The TLS codepoint used for the transport parameters changed between versions.  This needs to be addressed in the definition of being able to craft an appropriate Initial in the new version, because there are multiple paths one could choose:

- Require the client to include both TP extensions, so the server can respond only to the one used by the QUIC version it selects.
    - This pair of versions might be either compatible or incompatible, depending on whether the client includes both TPs in its ClientHello.
    - This solution isn't desirable long-term, because we don't want QUIC clients squatting on private-use space indefinitely.
- Require the server to modify the client's TLS message in well-defined ways as part of constructing an up-level Initial.
    - If the client doesn't have a way to make those changes to an in-progress handshake and/or restart a handshake by inputting a ClientHello, it will fail.
    - PSK binders could complicate this further; this would likely mean it's not possible to do some compatible version changes while doing 0-RTT.

So while the contents of the TP shouldn't be breaking between versions, we have an existence proof of breaking changes in the means of carrying the transport parameters.
