### ISSUE TITLE
Editor's Copy link is broken

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/version-negotiation#9]
Looks like `gh-pages` contains a draft, but GitHub isn't rendering it.  Is GitHub Pages enabled?

**Comment by LPardue** [comment]
Thanks @MikeBishop. Yes it seems link GitHub pages was not enabled. I've fixed that now and the page is hosted on https://quicwg.org/version-negotiation/draft-ietf-quic-version-negotiation.html

The link in README.md seems to be bogus. I've made PR #10 to fix it up.
