### ISSUE TITLE
What does "compatible" VN mean

### ISSUE THREAD

**Issue by ekr** [quicwg/version-negotiation#90]
Consider the case where the client and server both support v1 and v2 and prefer v2.

In the current draft, if the client puts v1 in the long header and the server responds with v2, that's called "compatible version negotiation". OTOH, if the client puts v2 in the long header and the server responds with v2, that's called, well, I'm not quite sure what. I guess not negotiation?

I think a better way to think about this is that the client is sending an Initial that is compatible with both versions and so both of these cases are compatible version negotiation.

**Comment by ekr** [comment]
Oops. Too late in the day: "OTOH, if the client puts v2 in the long header and the server responds with v2..."

**Comment by DavidSchinazi** [comment]
In the scenario where the client starts with v2 and the server responds with v2, I think of that as just "creating a v2 connection" without compatible version negotiation involved. Let's discuss this with the WG at IETF 113.
