### ISSUE TITLE
Recommendations for ALPN

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#92]
Can an ALPN label be used for multiple QUIC versions?

I think that the text should say something like:

> If the QUIC version uses ALPN, then an application protocol can use the same ALPN label for multiple QUIC versions iff:
> * the version of QUIC for which the ALPN was originally defined supports compatible version negotiation to any other QUIC version (this avoids performance issues)
> * the version of QUIC that is negotiated supports at least the features that the application depends on from the original QUIC version (e.g., if it uses streams, the new version has streams too)
> 
> It might be possible to share an ALPN across multiple versions with some added cleverness, but these are what we believe to be safe.

@ekr adds (and I wholly agree):

> Any application negotiation needs to be started over entirely when you do an incompatible version negotiation.

**Comment by DavidSchinazi** [comment]
I'm merging #91 into this one where @ekr said "The point is that your ALPN offer when you offer QUICvX shouldn't be dependent on if you did VN or not."
