### ISSUE TITLE
Choosing the original version

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#96]
Section 2.5 says unconditionally that the client chooses the most compatible version.

This isn't right, because the most compatible version isn't what it is looking to end up on.  What the client should choose is probably the most compatible version of those that are compatible (directionality ?) with its most preferred version.

**Comment by DavidSchinazi** [comment]
Rereading this, I think the directionality is correct in the existing text. But perhaps we could figure out better wording.
